[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Andre Julius <noromoron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutator = "^0.4.0"
itertools = "^0.9.0"